# https://github.com/docker/awesome-compose/tree/master/official-documentation-samples/django/
# https://github.com/docker/awesome-compose/blob/master/django/app/Dockerfile

services:
  db:
    image: postgres:17.2-alpine
    volumes:
      - ./docker-volume/data/db:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    # https://stackoverflow.com/questions/30063907/docker-compose-how-to-execute-multiple-commands
    command: sh -c "python myresumebuilder/manage.py migrate && python myresumebuilder/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
