# https://github.com/docker/awesome-compose/tree/master/official-documentation-samples/django/
# https://github.com/docker/awesome-compose/blob/master/django/app/Dockerfile

services:
  db:
    image: postgres:17.2-alpine
    volumes:
      - ./docker-volume/data/db:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10

  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
